---
- name: MariaDB 11.5 installation
  hosts: all
  become: yes
  vars:
    root_db_password: "password" 
 
  tasks:
    - name: Install necessary packages for repository setup
      apt:
        name:
          - apt-transport-https
          - curl
          - software-properties-common
          - dirmngr
          - gnupg2
        state: present

    - name: Create directory for keyrings
      file:
        path: /etc/apt/keyrings
        state: directory
        mode: '0755'

    - name: Download MariaDB signing key
      get_url:
        url: 'https://mariadb.org/mariadb_release_signing_key.pgp'
        dest: /etc/apt/keyrings/mariadb-keyring.pgp
        mode: '0644'

    - name: Add MariaDB repository to sources list
      copy:
        dest: /etc/apt/sources.list.d/mariadb.sources
        content: |
          # MariaDB 11 Rolling repository list - created 2024-10-18 07:28 UTC
          # https://mariadb.org/download/
          X-Repolib-Name: MariaDB
          Types: deb
          # deb.mariadb.org is a dynamic mirror if your preferred mirror goes offline. See https://mariadb.org/mirrorbits/ for details.
          # URIs: https://deb.mariadb.org/11/debian
          URIs: https://mirror.vpsfree.cz/mariadb/repo/11.rolling/debian
          Suites: bookworm
          Components: main
          Signed-By: /etc/apt/keyrings/mariadb-keyring.pgp
        mode: '0644'

    - name: Update apt cache
      apt:
        update_cache: yes

    - name: Install MariaDB server and client
      apt:
        pkg:
          - mariadb-server
          - mariadb-client
          - python3-pymysql
        state: present
 
    - name: Setup password for root
      mysql_user:
        login_unix_socket: /var/run/mysqld/mysqld.sock
        name: root
        host: localhost
        password: "{{ root_db_password }}"
        priv: '*.*:ALL,GRANT'
        state: present
        column_case_sensitive: false
 
    - name: Delete anonymous users
      mysql_user:
        login_user: root
        login_password: "{{ root_db_password }}"
        name: ''
        host_all: yes
        state: absent
        column_case_sensitive: false
        
    - name: Grant permissions for remote desktop
      mysql_query:
        login_user: root
        login_password: "{{ root_db_password }}"
        query: "GRANT ALL ON *.* TO 'root'@'%' IDENTIFIED BY '{{ root_db_password }}';"        
     
    - name: Allow SSL 
      command: a2enmod ssl
      notify: Restart Apache

    - name: Allow HTTPS (port 443)
      command: a2ensite default-ssl.conf
      notify: Restart Apache

    - name: Change bind-address for MariaDB
      lineinfile:
        path: /etc/mysql/mariadb.conf.d/50-server.cnf
        regexp: '^bind-address'
        line: 'bind-address = 0.0.0.0'
        state: present
        backrefs: yes

    - name: Restart MariaDB service
      service:
        name: mariadb
        state: restarted
        
  handlers:
    - name: Restart Apache
      service:
        name: apache2
        state: restarted
 